config/routes.rb
Rails.application.routes.draw do
  resources :faces
  resources :collections
  resources :rooms
  resources :users

  root to: 'landing#index'
  get 'welcome', to: 'landing#index', as: :welcome
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :faces
  has_many :rooms
end

app/models/face.rb
class Face < ApplicationRecord
  belongs_to :collection

  def self.available_image?
    !self.image.nil?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :collection
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :collections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  def index
    @collections = Collection.all
  end

  def show
    @face = Face.new
  end

  def new
    @collection = Collection.new
  end

  def edit
  end

  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: "Collection was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: "Collection was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:name, :theme, :user_id, :room_id)
    end
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
  before_action :set_face, only: %i[ show edit update destroy ]

  # GET /faces or /faces.json
  def index
    @faces = Face.all
  end

  # GET /faces/1 or /faces/1.json
  def show
  end

  # GET /faces/new
  def new
    @face = Face.new
  end

  # GET /faces/1/edit
  def edit
  end

  # POST /faces or /faces.json
  def create
    @face = Face.new(face_params)

    respond_to do |format|
      if @face.save
        format.html { redirect_to collection_path(@face.collection), notice: "Face was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faces/1 or /faces/1.json
  def update
    respond_to do |format|
      if @face.update(face_params)
        format.html { redirect_to @face, notice: "Face was successfully updated." }
        format.json { render :show, status: :ok, location: @face }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @face.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faces/1 or /faces/1.json
  def destroy
    @face.destroy
    respond_to do |format|
      format.html { redirect_to faces_url, notice: "Face was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_face
      @face = Face.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def face_params
      params.require(:face).permit(:name, :collection_id, :image)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :set_locale

  def index
    @user = User.new 
  end

  private

  def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
      @locale = params[:locale]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
    @collection = Collection.find(@room.collection_id)
    @collection.faces.sample.image.nil? ?  @your_image = @collection.faces.sample.name.downcase + ".png" : @your_image = @collection.faces.sample.image 
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name, :user_id, :open, :password, :collection_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_room_path, notice: "User was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/faces_helper.rb
module FacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collections/_form.html.erb
<%= simple_form_for @collection do |f| %>
  <%= f.input :name, required: true, input_html: { class: 'text_input', maxlength: 30 } %>
  <%= f.input :theme, required: true, input_html: { class: 'text_input',  maxlength: 15 } %>
  <%= f.hidden_field :user_id, value: 1 %>
  <div class="buttons">
    <%= f.button :submit, 'Criar Coleção', :class => "button_form"%>
    <%= link_to 'Cancelar', collections_path, :class => "button_back"%>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h2 class="page-title"> Editar Coleção </h2>

<div class="form_container medium">
  <%= render 'form', table: @collection %>
</div>

app/views/collections/index.html.erb
<h1 class="page-title"> Coleções </h1>
<h3 id="notice"><%= notice %></h3>
  <div class="btn_container">
    <%= link_to 'Criar Collection', new_collection_path, class: "btn btn--link" %>
  </div>

<div class="table_container">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Tema</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td><%= collection.name %></td>
          <td><%= collection.theme %></td>
          <td><%= link_to '✎', edit_collection_path(collection), class: 'btn btn--discrete' %>
          <%= link_to '◔◔', collection_path(collection), class: 'btn btn--show'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/collections/new.html.erb
<h2 class="page-title"> Criar Coleção  </h2>

<div class="form_container medium">
  <%= render 'form', table: @collection %>
</div>

app/views/collections/show.html.erb
<h1 class="page-title"><%= @collection.name %> </h1>
<h3 id="notice"><%= notice %></h3>

  <div class="btn_container">
    <div class="form_container medium">
      <%= simple_form_for @face do |f| %>
        <%= f.input :name, required: true, input_html: { class: 'text_input', maxlength: 15 } %>
        <%= f.input :image, label: 'Link da imagem: ', input_html: { class: 'text_input' } %>
        <%= f.hidden_field :collection_id, value: @collection.id %>
        <div class="buttons">
          <%= f.button :submit, 'Criar Face', :class => "button_form"%>
        </div>
      <% end %>
    </div>
  </div>

<div class="table_container">
  <table class="table">
    <thead>
      <tr>
        <th> Name </th>
        <th> Link da Imagem </th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>   
      <% @collection.faces.each do |face| %>
        <tr>
          <td><%= face.name %></td>
          <td><%= face.image if !face.image.nil? %></td>
          <td><%= link_to '✎', edit_face_path(face), class: 'btn btn--discrete' %></td>
          <td><%= link_to 'Destroy', face, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/faces/_form.html.erb
<%= simple_form_for @face do |f| %>
  <%= f.input :name, required: true, input_html: { class: 'text_input', maxlength: 15 } %>
  <%= f.input :image, label: 'Link da Image', required: true, input_html: { class: 'text_input' } %>
  <%= f.input :collection_id, collection: Collection.all , input_html: { class: 'text_input' } %>
  <div class="buttons">
    <%= f.button :submit, 'Criar Face', :class => "button_form"%>
    <%= link_to 'Cancelar', faces_path, :class => "button_back"%>
  </div>
<% end %>

app/views/faces/edit.html.erb
<h2 class="page-title"> Editar Face </h2>

<div class="form_container medium">
  <%= render 'form', table: @face %>
</div>

app/views/faces/index.html.erb
<h1 class="page-title"> Faces </h1>
<h3 id="notice"><%= notice %></h3>
  <div class="btn_container">
    <%= link_to 'Criar Face', new_face_path, class: "btn btn--link" %>
  </div>

<div class="table_container">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Imagem</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @faces.each do |face| %>
        <tr>
          <td><%= face.name %></td>
          <td><%= face.image %></td>
          <td><%= link_to '✎', edit_face_path(face), class: 'btn btn--discrete' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/faces/new.html.erb
<h2 class="page-title"> Criar Face </h2>

<div class="form_container medium">
  <%= render 'form', table: @face %>
</div>

app/views/faces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @face.name %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @face.collection %>
</p>

<%= link_to 'Edit', edit_face_path(@face) %> |
<%= link_to 'Back', faces_path %>

app/views/landing/index.html.erb
<div class="box">
  <div class="center">     
    <h2 class="page-title"> Escolha um username: </h2>
    
    <div class="form_container">
      <div class="btn_container">
        <%= simple_form_for @user do |f| %>
        <%= f.input :username, required: true, input_html: { class: 'text_input' } %>
        <%= f.button :submit, 'JOGAR', class: "btn btn--link" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer> Made with  ♥  (and hurry) by Aline Ramos </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceToFace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/header'%>
  </body>
</html>

app/views/rooms/_form.html.erb
<div class="box">
  <div class="center">     
    <h2 class="page-title"> Escolha uma Sala: </h2>
    
    <div class="form_container">
      <div class="btn_container">
        <%= simple_form_for @room do |f| %>
          <%= f.input :name, required: true, input_html: { class: 'text_input' } %>
          <%= f.input :collection_id, collection: Collection.all , input_html: { class: 'text_input' } %>
          <%= f.hidden_field :user_id, required: true, value: User.last.id %>
          <%= f.button :submit, 'JOGAR', class: "btn btn--link" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer> Made with  ♥  (and hurry) by Aline Ramos </footer>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Open</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.user %></td>
        <td><%= room.open %></td>
        <td><%= room.password %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<h1 class="page-title"> Room: <%= @room.name %> </h1>

<div class="container">  
  <div class="grid grid--auto-fill">
    <% @collection.faces.each do |face| %>
      <div class="grid__item"> 
        <% if !face.image.nil? %>
          <%= image_tag(face.image, :style => 'border-radius: 12px; width:180px; height:180px;')%>
        <% else %>
          <%= image_tag('https://roadie-metal.com/wp-content/uploads/2019/06/unknownpleasures.jpg', :style => 'border-radius: 12px; width:180px; height:180px;')%>
        <% end %>

        <div class="H1toH5">
          <label>
            <input type="checkbox" />
            <span class="seatButton"><%= face.name %></span>
          </label>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="image_container">
  <h2 style="margin-left:42%"> Você é: </h2>
  <p><%= image_tag(@your_image, :style => 'border-radius: 12px; width:180px; height:180px;')%>
</div>

app/views/shared/_header.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet">

<div class="header"> 
  <div class= "header--logo"> 
    <a href="/" > Face to Face </a> 
  </div>

      <div class= "header__menu"> 

      </div>
</div>

<script src="./assets/drop_menu.js"></script>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin, id: :user_admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1 class="page-title"> Usuários </h1>
<h3 id="notice"><%= notice %></h3>
  <div class="btn_container">
    <%= link_to 'Criar Usuário', new_user_path, class: "btn btn--link" %>
  </div>

<div class="table_container">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Admin</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td>
            <%= ' ⠀✔' if user.admin == true %>
          </td>
          <td><%= link_to '✎', edit_user_path(user), class: 'btn btn--discrete' %>
          <%= link_to '✘', user, method: :destroy, class: 'btn btn--delete', data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>